import type { Metadata } from "next";
import { Kanit } from 'next/font/google'
import { Roboto } from 'next/font/google'
import "./globals.css";

const kanit = Kanit({
  subsets: ["thai"],
  weight: ["400", "500", "600"],
  variable: "--font-kanit",
  display: "swap",
})

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["500", "700"],
  variable: "--font-roboto",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable} ${roboto.variable} antialiased scroll-smooth` }
      >
        {children}
      </body>
    </html>
  );
}
